MAHWEEN FATIMA
25915A6611
AIML

KNN CLASSIFIER TO CLASSIFY IRIS FLOWER

  importing all the required library files

In [ ]:
  import numpy as np
  import pandas as pd
  import matplotlib.pyplot as plt
  import seaborn as sns
  from sklearn import datasets
  from sklearn.neighbors import KNeighborsClassifier
  from sklearn.model_selection import train_test_split
  from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

importing and readinmg the dataset

In [ ]:
  from google.colab import drive
  drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/iris-data.csv')

In [ ]:
print(df.shape)

(150, 5)

In [ ]:
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
print(df.tail())

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
print(df.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

DATA PREPROCESSING (CLEANING THE UNWANTED DATA)

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(df.species)
df['species'] = le.transform(df.species)
print(df)

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [ ]:
print(df.species)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [ ]:
x=df.iloc[:,0:4]
y=df.iloc[:,4]

In [ ]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

Spliting the data into training and testing

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)

Builing the model k-Nearest Neighbors algorithm

In [ ]:
model = KNeighborsClassifier(n_neighbors=5)

In [ ]:
model

KNeighborsClassifier()

traing the model with traing data

In [ ]:
model_train = model.fit(x_train,y_train)

In [ ]:
model_train

KNeighborsClassifier()

test the model with testing Data

In [ ]:
y_pred = model_train.predict(x_test)

In [ ]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [ ]:
y_pred[0:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1])

In [ ]:
print(y_test[:10])

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
Name: species, dtype: int64

Evaluating the performane of the Model

In [ ]:
i=0
print("/n--------------------------------------------------------------------------")
print('%-25s %-25s %-25s' % ('Original Label', 'Predicted Label', 'Correct/Wrong'))
print("/n---------------------------------------------------------------------------")
for label in y_test[:10]:
  print('%-25s %-25s' % (label, y_pred[i]), end="")
  if (label == y_pred[i]):
    print('%-25s' % ('Correct'))
  else:
    print('%-25s' % ('Wrong'))
  i=i+1
  print("-----------------------------------------------------------------------------")

/n--------------------------------------------------------------------------
Original Label            Predicted Label           Correct/Wrong
/n---------------------------------------------------------------------------
1                         1                        Correct
-----------------------------------------------------------------------------
0                         0                        Correct
-----------------------------------------------------------------------------
2                         2                        Correct
-----------------------------------------------------------------------------
1                         1                        Correct
-----------------------------------------------------------------------------
1                         1                        Correct
-----------------------------------------------------------------------------
0                         0                        Correct
-----------------------------------------------------------------------------
1                         1                        Correct
-----------------------------------------------------------------------------
2                         2                        Correct
-----------------------------------------------------------------------------
1                         1                        Correct
-----------------------------------------------------------------------------
1                         1                        Correct
-----------------------------------------------------------------------------

Confusion Matrix

In [ ]:
import sklearn.metrics as metrics
confusion =confusion_matrix(y_test, y_pred)
confusion

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [ ]:
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

1.0

In [ ]:
print('Accuracy of the Classifier is %0.2f' % accuracy_score(y_test, y_pred))
print("----------------------------------------------------------------------")

Accuracy of the Classifier is 1.00
----------------------------------------------------------------------

In [ ]:
print("\nClassifion report:\n")
class_wise=metrics.classification_report(y_test,y_pred)
print(class_wise )

Classifion report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

predicting the new samples

In [ ]:
new_sample = [[5.1,3.5,1.4,0.2]]
prediction = model.predict(new_sample)
predicted_label = le.inverse_transform(prediction)
print("Predicted Label:", predicted_label)

Predicted Label: ['setosa']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(